/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Frames;

/**
 *
 * @author pc
 */
public class FrameCiudades extends javax.swing.JPanel {

    /**
     * Creates new form Ciudades
     */
    public FrameCiudades() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg3 = new javax.swing.JPanel();
        Buscarciudad = new javax.swing.JButton();
        title9 = new javax.swing.JLabel();
        BuscarCiudadtxt = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaCiudades = new javax.swing.JTable();
        EditarCiudad = new javax.swing.JButton();
        EliminarCiudad = new javax.swing.JButton();
        AgregarCiudad = new javax.swing.JButton();
        CodigoCiudadtxt = new javax.swing.JTextField();
        title10 = new javax.swing.JLabel();
        Nombreciudadtxt = new javax.swing.JTextField();
        title11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Actualizarbtn = new javax.swing.JButton();
        CodigoProvinciaBox = new javax.swing.JComboBox<>();
        title12 = new javax.swing.JLabel();

        bg3.setBackground(new java.awt.Color(255, 255, 255));
        bg3.setMinimumSize(new java.awt.Dimension(809, 544));

        Buscarciudad.setBackground(new java.awt.Color(153, 0, 0));
        Buscarciudad.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Buscarciudad.setForeground(new java.awt.Color(255, 255, 255));
        Buscarciudad.setText("Buscar");
        Buscarciudad.setBorderPainted(false);
        Buscarciudad.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Buscarciudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarciudadActionPerformed(evt);
            }
        });

        title9.setText("Codigo ciudad");

        BuscarCiudadtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarCiudadtxtActionPerformed(evt);
            }
        });

        tablaCiudades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO CIUDAD", "NOMBRE CIUDAD", "CODIGO PROVINCIA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablaCiudades.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane4.setViewportView(tablaCiudades);

        EditarCiudad.setBackground(new java.awt.Color(153, 0, 0));
        EditarCiudad.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        EditarCiudad.setForeground(new java.awt.Color(255, 255, 255));
        EditarCiudad.setText("Editar");
        EditarCiudad.setBorderPainted(false);

        EliminarCiudad.setBackground(new java.awt.Color(153, 0, 0));
        EliminarCiudad.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        EliminarCiudad.setForeground(new java.awt.Color(255, 255, 255));
        EliminarCiudad.setText("Eliminar");
        EliminarCiudad.setBorderPainted(false);
        EliminarCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarCiudadActionPerformed(evt);
            }
        });

        AgregarCiudad.setBackground(new java.awt.Color(153, 0, 0));
        AgregarCiudad.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        AgregarCiudad.setForeground(new java.awt.Color(255, 255, 255));
        AgregarCiudad.setText("Agregar");
        AgregarCiudad.setBorderPainted(false);

        CodigoCiudadtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodigoCiudadtxtActionPerformed(evt);
            }
        });
        CodigoCiudadtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CodigoCiudadtxtKeyTyped(evt);
            }
        });

        title10.setText("Codigo ciudad");

        Nombreciudadtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreciudadtxtActionPerformed(evt);
            }
        });

        title11.setText("Nombre ciudad");

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel2.setText("CIUDADES");

        Actualizarbtn.setBackground(new java.awt.Color(153, 0, 0));
        Actualizarbtn.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Actualizarbtn.setForeground(new java.awt.Color(255, 255, 255));
        Actualizarbtn.setText("Actualizar");
        Actualizarbtn.setBorderPainted(false);
        Actualizarbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Actualizarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarbtnActionPerformed(evt);
            }
        });

        title12.setText("Codigo Provincia");

        javax.swing.GroupLayout bg3Layout = new javax.swing.GroupLayout(bg3);
        bg3.setLayout(bg3Layout);
        bg3Layout.setHorizontalGroup(
            bg3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(bg3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(EditarCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EliminarCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
                    .addGroup(bg3Layout.createSequentialGroup()
                        .addGroup(bg3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(title9)
                            .addGroup(bg3Layout.createSequentialGroup()
                                .addComponent(BuscarCiudadtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Buscarciudad))
                            .addComponent(Actualizarbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(bg3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CodigoCiudadtxt, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                            .addComponent(title10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(bg3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bg3Layout.createSequentialGroup()
                                .addGroup(bg3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Nombreciudadtxt)
                                    .addComponent(title11, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(bg3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CodigoProvinciaBox, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(title12, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2))
                            .addGroup(bg3Layout.createSequentialGroup()
                                .addComponent(AgregarCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(35, 35, 35))
        );
        bg3Layout.setVerticalGroup(
            bg3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bg3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bg3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(bg3Layout.createSequentialGroup()
                            .addComponent(title9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6)
                            .addGroup(bg3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(BuscarCiudadtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Buscarciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(bg3Layout.createSequentialGroup()
                            .addComponent(title10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6)
                            .addComponent(CodigoCiudadtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(bg3Layout.createSequentialGroup()
                        .addGroup(bg3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(title11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(title12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(bg3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Nombreciudadtxt, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(CodigoProvinciaBox)))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bg3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Actualizarbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AgregarCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addGap(9, 9, 9)
                .addGroup(bg3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EditarCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EliminarCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarciudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarciudadActionPerformed

    }//GEN-LAST:event_BuscarciudadActionPerformed

    private void BuscarCiudadtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarCiudadtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarCiudadtxtActionPerformed

    private void EliminarCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarCiudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EliminarCiudadActionPerformed

    private void CodigoCiudadtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodigoCiudadtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodigoCiudadtxtActionPerformed

    private void NombreciudadtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreciudadtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreciudadtxtActionPerformed

    private void ActualizarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ActualizarbtnActionPerformed

    private void CodigoCiudadtxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CodigoCiudadtxtKeyTyped
        if (this.CodigoCiudadtxt.getText().length()>=4) {
            evt.consume();
        }
// TODO add your handling code here:
    }//GEN-LAST:event_CodigoCiudadtxtKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Actualizarbtn;
    public javax.swing.JButton AgregarCiudad;
    public javax.swing.JTextField BuscarCiudadtxt;
    public javax.swing.JButton Buscarciudad;
    public javax.swing.JTextField CodigoCiudadtxt;
    public javax.swing.JComboBox<String> CodigoProvinciaBox;
    public javax.swing.JButton EditarCiudad;
    public javax.swing.JButton EliminarCiudad;
    public javax.swing.JTextField Nombreciudadtxt;
    private javax.swing.JPanel bg3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JTable tablaCiudades;
    private javax.swing.JLabel title10;
    private javax.swing.JLabel title11;
    private javax.swing.JLabel title12;
    private javax.swing.JLabel title9;
    // End of variables declaration//GEN-END:variables
}
