/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Frames;

/**
 *
 * @author JONATHAN
 */
public class FrameProvincias extends javax.swing.JPanel {

    /**
     * Creates new form Provincias
     */
    public FrameProvincias() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        BuscarProvincia = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        buscadorProvincia = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProvincias = new javax.swing.JTable();
        editarProvincia = new javax.swing.JButton();
        eliminarProvincia = new javax.swing.JButton();
        agregarProvincia = new javax.swing.JButton();
        CodigoProvinciatxt = new javax.swing.JTextField();
        title1 = new javax.swing.JLabel();
        nombreProvinciatxt = new javax.swing.JTextField();
        title2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        actualizarbtn = new javax.swing.JButton();

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setMinimumSize(new java.awt.Dimension(809, 544));

        BuscarProvincia.setBackground(new java.awt.Color(153, 0, 0));
        BuscarProvincia.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        BuscarProvincia.setForeground(new java.awt.Color(255, 255, 255));
        BuscarProvincia.setText("Buscar");
        BuscarProvincia.setBorderPainted(false);
        BuscarProvincia.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BuscarProvincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarProvinciaActionPerformed(evt);
            }
        });

        title.setText("Codigo provincia");

        buscadorProvincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscadorProvinciaActionPerformed(evt);
            }
        });

        tablaProvincias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO PROVINCIA", "NOMBRE PROVINCIA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablaProvincias.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(tablaProvincias);

        editarProvincia.setBackground(new java.awt.Color(153, 0, 0));
        editarProvincia.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        editarProvincia.setForeground(new java.awt.Color(255, 255, 255));
        editarProvincia.setText("Editar");
        editarProvincia.setBorderPainted(false);

        eliminarProvincia.setBackground(new java.awt.Color(153, 0, 0));
        eliminarProvincia.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        eliminarProvincia.setForeground(new java.awt.Color(255, 255, 255));
        eliminarProvincia.setText("Eliminar");
        eliminarProvincia.setBorderPainted(false);
        eliminarProvincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarProvinciaActionPerformed(evt);
            }
        });

        agregarProvincia.setBackground(new java.awt.Color(153, 0, 0));
        agregarProvincia.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        agregarProvincia.setForeground(new java.awt.Color(255, 255, 255));
        agregarProvincia.setText("Agregar");
        agregarProvincia.setBorderPainted(false);

        CodigoProvinciatxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodigoProvinciatxtActionPerformed(evt);
            }
        });
        CodigoProvinciatxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CodigoProvinciatxtKeyTyped(evt);
            }
        });

        title1.setText("Codigo provincia");

        nombreProvinciatxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreProvinciatxtActionPerformed(evt);
            }
        });

        title2.setText("Nombre provincia");

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel3.setText("PROVINCIAS");

        actualizarbtn.setBackground(new java.awt.Color(153, 0, 0));
        actualizarbtn.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        actualizarbtn.setForeground(new java.awt.Color(255, 255, 255));
        actualizarbtn.setText("Actualizar");
        actualizarbtn.setBorderPainted(false);
        actualizarbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        actualizarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(bgLayout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(editarProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(eliminarProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(title)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(buscadorProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BuscarProvincia)))
                        .addGap(18, 18, 18)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CodigoProvinciatxt, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                            .addComponent(title1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nombreProvinciatxt)
                            .addComponent(title2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(agregarProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35))
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(actualizarbtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(bgLayout.createSequentialGroup()
                            .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6)
                            .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(buscadorProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BuscarProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(bgLayout.createSequentialGroup()
                            .addComponent(title1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6)
                            .addComponent(CodigoProvinciatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(title2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombreProvinciatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(agregarProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(actualizarbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editarProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eliminarProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)))
                .addGap(58, 58, 58))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarProvinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarProvinciaActionPerformed

    }//GEN-LAST:event_BuscarProvinciaActionPerformed

    private void buscadorProvinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscadorProvinciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscadorProvinciaActionPerformed

    private void eliminarProvinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarProvinciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminarProvinciaActionPerformed

    private void CodigoProvinciatxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodigoProvinciatxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodigoProvinciatxtActionPerformed

    private void nombreProvinciatxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreProvinciatxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreProvinciatxtActionPerformed

    private void actualizarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_actualizarbtnActionPerformed

    private void CodigoProvinciatxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CodigoProvinciatxtKeyTyped
        if (this.CodigoProvinciatxt.getText().length()>=4) {
            evt.consume();
        }
    }//GEN-LAST:event_CodigoProvinciatxtKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BuscarProvincia;
    public javax.swing.JTextField CodigoProvinciatxt;
    public javax.swing.JButton actualizarbtn;
    public javax.swing.JButton agregarProvincia;
    private javax.swing.JPanel bg;
    public javax.swing.JTextField buscadorProvincia;
    public javax.swing.JButton editarProvincia;
    public javax.swing.JButton eliminarProvincia;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField nombreProvinciatxt;
    public javax.swing.JTable tablaProvincias;
    private javax.swing.JLabel title;
    private javax.swing.JLabel title1;
    private javax.swing.JLabel title2;
    // End of variables declaration//GEN-END:variables
}
