/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Frames;

/**
 *
 * @author pc
 */
public class FrameProductos extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public FrameProductos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        buscarProductobtn = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        buscadorProductostxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        editarProductobtn = new javax.swing.JButton();
        eliminarProductobtn = new javax.swing.JButton();
        agregarProductobtn = new javax.swing.JButton();
        codigoProductotxt = new javax.swing.JTextField();
        title1 = new javax.swing.JLabel();
        nombreProductotxt = new javax.swing.JTextField();
        title2 = new javax.swing.JLabel();
        codigoProveedortxt = new javax.swing.JTextField();
        title3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setMinimumSize(new java.awt.Dimension(809, 490));
        bg.setPreferredSize(new java.awt.Dimension(809, 490));

        buscarProductobtn.setBackground(new java.awt.Color(153, 0, 0));
        buscarProductobtn.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        buscarProductobtn.setForeground(new java.awt.Color(255, 255, 255));
        buscarProductobtn.setText("Buscar");
        buscarProductobtn.setBorderPainted(false);
        buscarProductobtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        buscarProductobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarProductobtnActionPerformed(evt);
            }
        });

        title.setText("CODIGO PRODUCTO");

        buscadorProductostxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscadorProductostxtActionPerformed(evt);
            }
        });

        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "CODIGO", "NOMBRE", "CODIGO PROVEEDOR"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablaProductos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(tablaProductos);

        editarProductobtn.setBackground(new java.awt.Color(153, 0, 0));
        editarProductobtn.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        editarProductobtn.setForeground(new java.awt.Color(255, 255, 255));
        editarProductobtn.setText("Editar");
        editarProductobtn.setBorderPainted(false);

        eliminarProductobtn.setBackground(new java.awt.Color(153, 0, 0));
        eliminarProductobtn.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        eliminarProductobtn.setForeground(new java.awt.Color(255, 255, 255));
        eliminarProductobtn.setText("Eliminar");
        eliminarProductobtn.setBorderPainted(false);
        eliminarProductobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarProductobtnActionPerformed(evt);
            }
        });

        agregarProductobtn.setBackground(new java.awt.Color(153, 0, 0));
        agregarProductobtn.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        agregarProductobtn.setForeground(new java.awt.Color(255, 255, 255));
        agregarProductobtn.setText("Agregar");
        agregarProductobtn.setBorderPainted(false);

        codigoProductotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoProductotxtActionPerformed(evt);
            }
        });

        title1.setText("CODIGO PRODUCTO");

        nombreProductotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreProductotxtActionPerformed(evt);
            }
        });

        title2.setText("NOMBRE");

        codigoProveedortxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoProveedortxtActionPerformed(evt);
            }
        });

        title3.setText("CODIGO PROVEEDOR");

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel2.setText("PRODUCTOS");

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(title))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(buscadorProductostxt, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buscarProductobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGap(560, 560, 560)
                                .addComponent(editarProductobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(eliminarProductobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(title2)
                                    .addComponent(nombreProductotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(title1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(codigoProductotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(title3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(codigoProveedortxt, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(agregarProductobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 34, Short.MAX_VALUE)))
                .addContainerGap())
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(title)
                        .addGap(6, 6, 6)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buscadorProductostxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buscarProductobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addGap(20, 20, 20)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(title2)
                                .addGap(6, 6, 6)
                                .addComponent(nombreProductotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(title1)
                                .addGap(6, 6, 6)
                                .addComponent(codigoProductotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                        .addGap(8, 8, 8)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editarProductobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eliminarProductobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(title3)
                        .addGap(2, 2, 2)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(codigoProveedortxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(agregarProductobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buscarProductobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarProductobtnActionPerformed

    }//GEN-LAST:event_buscarProductobtnActionPerformed

    private void buscadorProductostxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscadorProductostxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscadorProductostxtActionPerformed

    private void eliminarProductobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarProductobtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminarProductobtnActionPerformed

    private void codigoProductotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoProductotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoProductotxtActionPerformed

    private void nombreProductotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreProductotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreProductotxtActionPerformed

    private void codigoProveedortxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoProveedortxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoProveedortxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton agregarProductobtn;
    private javax.swing.JPanel bg;
    public javax.swing.JTextField buscadorProductostxt;
    public javax.swing.JButton buscarProductobtn;
    public javax.swing.JTextField codigoProductotxt;
    public javax.swing.JTextField codigoProveedortxt;
    public javax.swing.JButton editarProductobtn;
    public javax.swing.JButton eliminarProductobtn;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField nombreProductotxt;
    public javax.swing.JTable tablaProductos;
    private javax.swing.JLabel title;
    private javax.swing.JLabel title1;
    private javax.swing.JLabel title2;
    private javax.swing.JLabel title3;
    // End of variables declaration//GEN-END:variables
}
