/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

import Frames.FrameClientes;
import Frames.FrameFacturas;
import Frames.FrameProductos;
import Frames.FrameProveedores;
import com.formdev.flatlaf.intellijthemes.FlatLightFlatIJTheme;
import com.formdev.flatlaf.intellijthemes.FlatVuesionIJTheme;
import interfaces.Fechas;
import java.awt.BorderLayout;
import static java.time.Instant.now;
import java.time.LocalDate;
import javax.swing.JPanel;

/**
 *
 * @author pc
 */
public class Principal extends javax.swing.JFrame implements Fechas {

    private int x,y,mousex,mousey;
    public Principal() {
        initComponents();
        Fecha();
        this.setLocationRelativeTo(null);
    }
    




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        BotonProductos = new javax.swing.JButton();
        BotonProveedor = new javax.swing.JButton();
        BotonCompra = new javax.swing.JButton();
        BotonClientes = new javax.swing.JButton();
        BotonFactura = new javax.swing.JButton();
        BotonKardex = new javax.swing.JButton();
        BotonVentas = new javax.swing.JButton();
        BotonProvincia = new javax.swing.JButton();
        BotonComprasGeneradas = new javax.swing.JButton();
        BotonCiudad = new javax.swing.JButton();
        BotonUsuarios = new javax.swing.JButton();
        CABECERA = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Fecha = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Contenido = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1100, 618));

        jPanel2.setBackground(new java.awt.Color(204, 0, 51));

        BotonProductos.setBackground(new java.awt.Color(153, 0, 0));
        BotonProductos.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        BotonProductos.setForeground(new java.awt.Color(255, 255, 255));
        BotonProductos.setText("PRODUCTOS");
        BotonProductos.setBorder(null);
        BotonProductos.setBorderPainted(false);
        BotonProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonProductos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BotonProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonProductosActionPerformed(evt);
            }
        });

        BotonProveedor.setBackground(new java.awt.Color(153, 0, 0));
        BotonProveedor.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        BotonProveedor.setForeground(new java.awt.Color(255, 255, 255));
        BotonProveedor.setText("PROOVEDOR");
        BotonProveedor.setBorder(null);
        BotonProveedor.setBorderPainted(false);
        BotonProveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonProveedor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BotonProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonProveedorActionPerformed(evt);
            }
        });

        BotonCompra.setBackground(new java.awt.Color(153, 0, 0));
        BotonCompra.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        BotonCompra.setForeground(new java.awt.Color(255, 255, 255));
        BotonCompra.setText("COMPRA");
        BotonCompra.setBorder(null);
        BotonCompra.setBorderPainted(false);
        BotonCompra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonCompra.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BotonCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCompraActionPerformed(evt);
            }
        });

        BotonClientes.setBackground(new java.awt.Color(153, 0, 0));
        BotonClientes.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        BotonClientes.setForeground(new java.awt.Color(255, 255, 255));
        BotonClientes.setText("CLIENTES");
        BotonClientes.setBorder(null);
        BotonClientes.setBorderPainted(false);
        BotonClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonClientes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BotonClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonClientesActionPerformed(evt);
            }
        });

        BotonFactura.setBackground(new java.awt.Color(153, 0, 0));
        BotonFactura.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        BotonFactura.setForeground(new java.awt.Color(255, 255, 255));
        BotonFactura.setText("FACTURA");
        BotonFactura.setBorder(null);
        BotonFactura.setBorderPainted(false);
        BotonFactura.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonFactura.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BotonFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonFacturaActionPerformed(evt);
            }
        });

        BotonKardex.setBackground(new java.awt.Color(153, 0, 0));
        BotonKardex.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        BotonKardex.setForeground(new java.awt.Color(255, 255, 255));
        BotonKardex.setText("KARDEX");
        BotonKardex.setBorder(null);
        BotonKardex.setBorderPainted(false);
        BotonKardex.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonKardex.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BotonKardex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonKardexActionPerformed(evt);
            }
        });

        BotonVentas.setBackground(new java.awt.Color(153, 0, 0));
        BotonVentas.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        BotonVentas.setForeground(new java.awt.Color(255, 255, 255));
        BotonVentas.setText("VENTAS GENERADAS");
        BotonVentas.setBorder(null);
        BotonVentas.setBorderPainted(false);
        BotonVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonVentas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        BotonProvincia.setBackground(new java.awt.Color(153, 0, 0));
        BotonProvincia.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        BotonProvincia.setForeground(new java.awt.Color(255, 255, 255));
        BotonProvincia.setText("PROVINCIA");
        BotonProvincia.setBorder(null);
        BotonProvincia.setBorderPainted(false);
        BotonProvincia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonProvincia.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        BotonComprasGeneradas.setBackground(new java.awt.Color(153, 0, 0));
        BotonComprasGeneradas.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        BotonComprasGeneradas.setForeground(new java.awt.Color(255, 255, 255));
        BotonComprasGeneradas.setText("COMPRAS GENERADAS");
        BotonComprasGeneradas.setBorder(null);
        BotonComprasGeneradas.setBorderPainted(false);
        BotonComprasGeneradas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonComprasGeneradas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        BotonCiudad.setBackground(new java.awt.Color(153, 0, 0));
        BotonCiudad.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        BotonCiudad.setForeground(new java.awt.Color(255, 255, 255));
        BotonCiudad.setText("CIUDAD");
        BotonCiudad.setBorder(null);
        BotonCiudad.setBorderPainted(false);
        BotonCiudad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonCiudad.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        BotonUsuarios.setBackground(new java.awt.Color(153, 0, 0));
        BotonUsuarios.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        BotonUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        BotonUsuarios.setText("USUARIOS");
        BotonUsuarios.setBorder(null);
        BotonUsuarios.setBorderPainted(false);
        BotonUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BotonUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonUsuariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BotonClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BotonProductos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BotonProveedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BotonFactura, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BotonCompra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BotonKardex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BotonProvincia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BotonComprasGeneradas, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
            .addComponent(BotonVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BotonCiudad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BotonUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(BotonProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonKardex, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonComprasGeneradas, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CABECERA.setBackground(new java.awt.Color(204, 0, 51));
        CABECERA.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                CABECERAMouseDragged(evt);
            }
        });
        CABECERA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CABECERAMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("TOYOTA");

        Fecha.setFont(new java.awt.Font("Roboto", 1, 22)); // NOI18N
        Fecha.setForeground(new java.awt.Color(255, 255, 255));
        Fecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Fecha.setText("{dayname} {day} de {month} de {year}");

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout CABECERALayout = new javax.swing.GroupLayout(CABECERA);
        CABECERA.setLayout(CABECERALayout);
        CABECERALayout.setHorizontalGroup(
            CABECERALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CABECERALayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addGap(73, 73, 73)
                .addComponent(Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 442, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        CABECERALayout.setVerticalGroup(
            CABECERALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CABECERALayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CABECERALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Fecha))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CABECERALayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        Contenido.setBackground(new java.awt.Color(255, 255, 255));
        Contenido.setMinimumSize(new java.awt.Dimension(855, 550));
        Contenido.setPreferredSize(new java.awt.Dimension(855, 550));
        Contenido.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CABECERA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Contenido, javax.swing.GroupLayout.DEFAULT_SIZE, 885, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(CABECERA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Contenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonProductosActionPerformed
        
    }//GEN-LAST:event_BotonProductosActionPerformed

    private void BotonProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonProveedorActionPerformed
       
    }//GEN-LAST:event_BotonProveedorActionPerformed

    private void BotonClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonClientesActionPerformed
        
    }//GEN-LAST:event_BotonClientesActionPerformed

    private void BotonFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonFacturaActionPerformed
        
    }//GEN-LAST:event_BotonFacturaActionPerformed

    private void BotonCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonCompraActionPerformed

    private void BotonKardexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonKardexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonKardexActionPerformed

    private void BotonUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonUsuariosActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void CABECERAMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CABECERAMouseDragged
        x = evt.getXOnScreen();
        y = evt.getYOnScreen();
        this.setLocation(x-mousex, y-mousey);
    }//GEN-LAST:event_CABECERAMouseDragged

    private void CABECERAMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CABECERAMousePressed
        mousex = evt.getX();
        mousey = evt.getY();
    }//GEN-LAST:event_CABECERAMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BotonCiudad;
    public javax.swing.JButton BotonClientes;
    public javax.swing.JButton BotonCompra;
    public javax.swing.JButton BotonComprasGeneradas;
    public javax.swing.JButton BotonFactura;
    public javax.swing.JButton BotonKardex;
    public javax.swing.JButton BotonProductos;
    public javax.swing.JButton BotonProveedor;
    public javax.swing.JButton BotonProvincia;
    public javax.swing.JButton BotonUsuarios;
    public javax.swing.JButton BotonVentas;
    private javax.swing.JPanel CABECERA;
    public javax.swing.JPanel Contenido;
    private javax.swing.JLabel Fecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void Fecha() {
          LocalDate ahora = LocalDate.now();
        int año  = ahora.getYear();
        int dia = ahora.getDayOfMonth();
        int mes = ahora.getMonthValue();
        String[] meses ={"Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","agosto","Septiembre","Octubre","Noviembre","diciembre"};
        Fecha.setText(dia+" de "+meses[mes-1]+" de "+año);
    }
}
